
source 'https://github.com/Aaronwk/DKCloudSource'

use_frameworks!

platform :ios, '10.0'

target 'DKCloudFramework_Example' do
#  pod 'DKCloudFramework', :path => '../'
  pod 'DKCloudFramework'

  target 'DKCloudFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
